user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
	worker_connections 768;
}

http {
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=askme_cache:15m max_size=100m inactive=10m use_temp_path=off;

    include /etc/nginx/mime.types;
	default_type application/octet-stream;

	gzip on;

    upstream askme {
        server askme-service:8000;
    }

    server {
        listen 80 default_server;
        server_name askme.com;

        access_log /var/log/nginx/askme.access.log;
        error_log /var/log/nginx/askme.error.log;

        location / {
            proxy_pass http://askme;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_cache askme_cache;
            proxy_cache_valid 200 302 10m;
            proxy_cache_valid 404      1m;
        }

        location ^~ /upload/ {
            root /askme-service/;
            add_header Cache-Control "public, max-age=2592000";
            gzip on;
        }

        location ^~ /static/ {
            root /askme-service/;
            add_header Cache-Control "public, max-age=2592000";
            gzip on;
        }

        location ~* \.(js|css|png|jpg)$ {
            root /askme-service/static/;
            add_header Cache-Control "public, max-age=2592000";
            gzip on;
        }
    }
}